In [13]:
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KDTree
import numpy as np
from sklearn import preprocessing
# parsing and preprocessing :
import gmparser as parse

In [4]:
data, encoded_data,X,y= parse.main()

In [5]:
X2=preprocessing.scale(X)

In [7]:
nbrs=NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(X)

In [8]:
distances,indices=nbrs.kneighbors(X)

In [9]:
indices

array([[ 0, 24],
       [ 1,  7],
       [ 2,  3],
       [ 3,  2],
       [ 4, 36],
       [ 5, 10],
       [ 6, 11],
       [ 7,  1],
       [ 8, 15],
       [ 9, 17],
       [10, 33],
       [11, 22],
       [12, 35],
       [13, 17],
       [14, 31],
       [15,  8],
       [16, 23],
       [17,  9],
       [18,  1],
       [19, 25],
       [20, 32],
       [21, 32],
       [22, 11],
       [23, 16],
       [24, 19],
       [25, 19],
       [26, 30],
       [27, 25],
       [28, 30],
       [29, 12],
       [30, 26],
       [31, 14],
       [32, 20],
       [33, 10],
       [34, 37],
       [35, 16],
       [36,  4],
       [37, 34],
       [38,  8]])

In [10]:
distances

array([[ 0.        , 36.28291609],
       [ 0.        ,  6.56220237],
       [ 0.        ,  3.16227766],
       [ 0.        ,  3.16227766],
       [ 0.        ,  7.25844336],
       [ 0.        , 12.49249775],
       [ 0.        , 14.38419271],
       [ 0.        ,  6.56220237],
       [ 0.        , 12.31909088],
       [ 0.        , 16.42926961],
       [ 0.        ,  8.56796359],
       [ 0.        ,  7.6290563 ],
       [ 0.        , 15.28602303],
       [ 0.        , 16.45364701],
       [ 0.        ,  7.24033839],
       [ 0.        , 12.31909088],
       [ 0.        ,  6.11228272],
       [ 0.        , 16.42926961],
       [ 0.        , 13.93735986],
       [ 0.        ,  7.41619849],
       [ 0.        ,  5.40485893],
       [ 0.        , 11.22062832],
       [ 0.        ,  7.6290563 ],
       [ 0.        ,  6.11228272],
       [ 0.        , 18.49540483],
       [ 0.        ,  7.41619849],
       [ 0.        ,  7.35272058],
       [ 0.        , 18.08825586],
       [ 0.        ,

In [11]:
nbrs.kneighbors_graph(X).toarray()

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [14]:
kdt = KDTree(X, leaf_size=30, metric='euclidean')

In [15]:
kdt.query(X, k=2, return_distance=False) 

array([[ 0, 24],
       [ 1,  7],
       [ 2,  3],
       [ 3,  2],
       [ 4, 36],
       [ 5, 10],
       [ 6, 11],
       [ 7,  1],
       [ 8, 15],
       [ 9, 17],
       [10, 33],
       [11, 22],
       [12, 35],
       [13, 17],
       [14, 31],
       [15,  8],
       [16, 23],
       [17,  9],
       [18,  1],
       [19, 25],
       [20, 32],
       [21, 32],
       [22, 11],
       [23, 16],
       [24, 19],
       [25, 19],
       [26, 30],
       [27, 25],
       [28, 30],
       [29, 12],
       [30, 26],
       [31, 14],
       [32, 20],
       [33, 10],
       [34, 37],
       [35, 16],
       [36,  4],
       [37, 34],
       [38,  8]])